### ISSUE TITLE
不支持Windows11新菜单

### ISSUE THREAD

**Issue by sceraser** [qianfanguojin/windowsterminal-menu#1]
![image](https://user-images.githubusercontent.com/42718757/148689401-515b2ee0-8bb0-4c53-b3cc-1b48ededb792.png)

**Comment by qianfanguojin** [comment]
> ![image](https://user-images.githubusercontent.com/42718757/148689401-515b2ee0-8bb0-4c53-b3cc-1b48ededb792.png)

嗯，当时是在 `Windows10` 上测试的，Win11修改了右键菜单的配置方式，暂时还未解决。
更多选项中是可以看到的

**Comment by qianfanguojin** [comment]
目前已经通过第三方工具临时实现了 win11 右键菜单 03938ba24be0994f4d85d13be9f93c82341272aa 。
