### ISSUE TITLE
选择特定ubuntu版本而非默认版本的shell时，路径依然是家目录而不是当前目录

### ISSUE THREAD

**Issue by maru7777** [qianfanguojin/windowsterminal-menu#2]
不论在哪里右击打开终端 ，路径都默认在家目录下

**Comment by qianfanguojin** [comment]
https://github.com/lextm/windowsterminal-shell/issues/44#issuecomment-1525030851 

原仓库的 ISSUE 也提到了这个问题，你可以按照这条回复检查 windows terminal 的设置看看。
